name: Heroku Deployment

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present

  build-and-deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"

      - name: npm install & build
        run: |
          npm install
          npm run build --if-present

      - name: "Deploy to Heroku Web App"
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}

  discord-notification:
    if: always()
    name: Workflow Status
    needs:
      - build
      - build-and-deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: get version
        id: version
        uses: notiz-dev/github-action-json-property@release
        with:
          path: "package.json"
          prop_path: "version"
      - run: echo ${{steps.version.outputs.prop}}

      - name: Discord Workflow Notifications (Deployment Completion)
        uses: nobrayner/discord-webhook@v1
        with:
          github-token: ${{secrets.TOKEN_GITHUB}}
          discord-webhook: ${{secrets.DISCORD_WEBHOOK_URI}}
          username: "GitHub CI/CD"
          avatar-url: "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png"
          title: DJSR DAQ API v${{steps.version.outputs.prop}}
